### ISSUE TITLE
Dear author, when will you open source your code?

### ISSUE THREAD

**Issue by Soverngity** [robot-learning-freiburg/LCDNet#1]
Dear author, when will you open source your code?

**Comment by avalada** [comment]
Thanks for your interest. We will release the code once we receive the decision on the paper from the journal. We just submitted it to review so it would probably take a few months. Stay tuned!

**Comment by Coderx7** [comment]
@avalada its been a full year already, do you plan on releasing any code anytime soon? 

Edit:
It seems your paper is also accepted! (Accepted to IEEE Transactions on Robotics (T-RO), 2022)

**Comment by cattaneod** [comment]
@Coderx7 @Soverngity Sorry for the long wait, but the review process of journals is very long, it took more that a year since we first submitted our paper.
But finally, few days ago our paper has been accepted to T-RO!

I'm running a training to check that everything is working properly, and if nothing goes wrong with the training, I will publish the code by the end of the week!

**Comment by Coderx7** [comment]
Yes, I know, I just wanted to make sure everything is good. 
Its great to hear that, looking forward to it :)
